//
//  FontRegistration.swift
//  iWrestle
//

import CoreText
import Foundation

/// The Info.plist is generated by the build system and `UIAppFonts` has no
/// `INFOPLIST_KEY_` equivalent, so the bundled Geist faces are registered with
/// CoreText at launch instead. The `.ttf` files live in `Resources/Fonts` and
/// are copied into the bundle by the synchronized root group.
enum AppFonts {
    static func registerAll() {
        let urls = Bundle.main.urls(forResourcesWithExtension: "ttf", subdirectory: nil) ?? []
        for url in urls where url.lastPathComponent.hasPrefix("Geist") {
            var error: Unmanaged<CFError>?
            if !CTFontManagerRegisterFontsForURL(url as CFURL, .process, &error) {
                // Already-registered fonts report an error we can ignore; anything
                // else means the typography falls back to system fonts.
                #if DEBUG
                print("Font registration skipped for \(url.lastPathComponent): \(String(describing: error?.takeUnretainedValue()))")
                #endif
            }
        }
    }
}
